schema_version = "1.0.0"

id = "addon_reloader"
name = "Addon Reloader"
version = "1.5.8"
tagline = "Fast Reload Addon / Extension"
maintainer = "letleon <letleon@163.com>"
type = "add-on"
copyright = ["2024 letleon"]

website = "https://github.com/0xletleon/AddonReloader"
tags = ["System", "Development"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Used to open the selected plugin folder"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/*.bat",
  "/*.jpg",
  "/*.png",
  "/.gitignore",
  "/*.md"
]